#!/usr/bin/env node

'use strict'

var c= require("skilstak-colors");

console.log(c.clear);

for (var n = 1; n <= 12; n++) {
console.log(n + c.multi(" Badger"));
}

for (var m = 13; m <= 14; m++) {
  console.log(m + c.multi(" Mushroom"));
}
